version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - dev.env
